name: Doxygen
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen install
      run: sudo apt-get install -y doxygen graphviz 
    - name: Doxygen
      run: doxygen
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
        force_orphan: true